name: agrimind_site
description: "Agrimind Landing Page"

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=3.9.0 <4.0.0"
  flutter: ">=3.35.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  
  # Core Package (shared services)
  core:
    path: ../../packages/core

  # UI Components
  google_fonts: ^6.2.1
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting

flutter:
  uses-material-design: true
  assets:
    - lib/assets/
    - assets/imagens/app_icons/
