name: app_petiveti
description: Aplicativo veterinário com arquitetura SOLID - Migração do app-petiveti
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Core Package - Serviços compartilhados (Firebase, Riverpod, Hive, GetIt, Injectable, Provider, dartz, equatable, etc.)
  core:
    path: ../../packages/core
  get_it: any
  injectable: any
  connectivity_plus: any
  dartz: any
  cloud_firestore: any
  firebase_auth: any
  hive: any
  flutter_local_notifications: any
  timezone: any
  riverpod_annotation: any
  intl: any
  flutter_riverpod: any
  url_launcher: any
  firebase_core: any
  package_info_plus: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
